services:
  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres
    container_name: postgresql-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-init0db.d/create_database.sql
    ports:
      - '5435:5432'

volumes:
  postgres_data:
